image: registry.gitlab.com/sebastians90/docker-hspec:latest

ex2:
  script:
    - cd ex2
    - runhaskell Tests.hs --color
  only:
    changes:
      - ex2/*.{hs,lhs}

ex3:
  script:
    - cd ex3
    - runhaskell Tests.hs --color
  only:
    changes:
      - ex3/*.{hs,lhs}

ex4:
  script:
    - cd ex4
    - runhaskell Tests.hs --color
  only:
    changes:
      - ex4/*.{hs,lhs}
