image: registry.gitlab.com/sebastians90/docker-hspec:latest

ex2:
  script:
    - cd ex2
    - runhaskell Tests.hs --color
  only:
    changes:
      - ex2/*.{hs,lhs}

ex3:
  script:
    - cd ex3
    - runhaskell Tests.hs --color
  only:
    changes:
      - ex3/*.{hs,lhs}

ex4:
  script:
    - cd ex4
    - runhaskell Tests.hs --color
  only:
    changes:
      - ex4/*.{hs,lhs}

ex5:
  script:
    - cd ex5
    - ghc -Wall Hardware
    - ghc -Wall BoolMonoids
    - ghc -Wall MapReduce
    - runhaskell Tests.hs --color
  only:
    changes:
      - ex5/*.{hs,lhs}

ex6:
  script:
    - cd ex6
    - ghc -Wall Huffman
    - runhaskell Tests.hs --color
  only:
    changes:
      - ex6/*.{hs,lhs}
